### PR TITLE
Support for macOS

### PR DESCRIPTION
**Pull request by andystanton**
This builds on top of @jpbruyere's Linux branch for #1. I added ifdefs to choose the right includes and definitions, as well as using the first command line argument as the target font face. This should mean that the code will compile and run on any of the supported platforms without changes.

Merging this change would be great as then the demo works on three major platforms. Perhaps @kocsis1david and @jpbruyere can test the changes locally to verify that this claim is true? :)

The changes are:
* Adds a command line argument for font face.
* Adds a Makefile for triggering the build and running on macOS and Linux.
* Adds support for macOS.
* Updates includes and definitions to allow compilation to work on Windows, Linux & macOS.
* Updates README with instructions for macOS and placeholder instructions for Linux.

### CODE REVIEW

**Review by jpbruyere — APPROVED** [review]
That's OK on linux, and an happy new year :-)

**Comment by jpbruyere** [comment]
@andystanton CMake is generating the makefile, so maybe it's better to remove it from the commit. You may had an helper message telling to the user to provide a font file path.

**Comment by andystanton** [comment]
The `run-linux` and `run-macos` targets are unnecessary and I added them because I am lazy. I'm happy to remove these :)

The build target in the makefile is for convenience to trigger the CMake build and then run the makefiles that CMake generates. It runs:

```
mkdir -p build
cd build
cmake ..
make
```

The reason for creating a build folder is that if you run `cmake .` in the project root you end up with all the cmake files there, so this keeps it cleaner.

I think this part of the makefile should stay, but the commands could be listed in the README instead. What do you think?

**Comment by jpbruyere** [comment]
I always compile cmake projects in a build forlder. I didn't make a pull request because I've not cleaned the cmakefile.txt (remove xxd and make optional the re-compilation of shaders to spir-v). also I've no recent window platform to test win config.

**Comment by kocsis1david** [comment]
I can test on Windows, but I'm not good at cmake.
If I use cmake, can it generate the Visual Studio project files? In this case VS files can be deleted as well.

**Comment by jpbruyere** [comment]
Yes, cmake should generate vs files if requested, but I've never test it by myself. I have removed XXD from cmake and add a shader copy if glslc is not present, it is in my linux branch, I don't know if it will automatically be added to this pull request.

**Comment by andystanton** [comment]
@jpbruyere I merged your latest changes, removed the makefile and updated the README with the instructions using CMake and the generated makefiles only.

The demo now requires a font to be passed in as the first argument when the program is executed.

@kocsis1david I am unable to test on Windows, but it looks like there are two ways to load from CMake with Visual Studio - either generate the project files, or open the CMakeLists.txt from Visual Studio: https://preshing.com/20170511/how-to-build-a-cmake-based-project/#building-with-visual-studio

As a side note, thanks for making this demo @kocsis1david - I've integrated it into a test Vulkan project I'm working on:

screenshot 2019-01-02 at 16 06 37

**Comment by kocsis1david** [comment]
Sorry for not responding earlier, thanks for the PR, I'm glad that you could integrate it.

**Pull request merged**
